from groq import Groq
from dotenv import load_dotenv
import os
import json

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

MULTI_ARCHITECT_PROMPT = """
You are an AI panel of senior architects:
- Software Architect
- Backend Architect
- Database Architect
- Security Architect

Convert the HIGH-LEVEL BUSINESS REQUIREMENT below into
LOW-LEVEL TECHNICAL SPECIFICATIONS.

STRICT RULES:
- Output ONLY valid JSON
- No explanations
- No markdown
- No comments
- Follow schema exactly

Business Requirement:
{requirement_text}

JSON SCHEMA:
{{
  "assumptions": ["string"],
  "missing_requirements": ["string"],
  "modules": [
    {{
      "name": "string",
      "description": "string",
      "responsibilities": ["string"]
    }}
  ],
  "database_schema": {{
    "TableName": {{
      "field_name": "datatype"
    }}
  }},
  "pseudo_code": {{
    "ModuleName": ["step"]
  }},
  "architecture_diagram": "plain text mermaid"
}}
"""


def extract_json(text):
    try:
        start = text.index("{")
        end = text.rindex("}") + 1
        return text[start:end]
    except ValueError:
        return None

def generate_specifications(requirement_text):
    prompt = MULTI_ARCHITECT_PROMPT.format(
        requirement_text=requirement_text
    )

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            {
                "role": "system",
                "content": "You must return ONLY valid JSON."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        max_tokens=2000
    )

    raw_output = response.choices[0].message.content.strip()
    json_text = extract_json(raw_output)

    if not json_text:
        return {
            "error": "No JSON detected from LLM",
            "raw_output": raw_output
        }

    try:
        return json.loads(json_text)
    except json.JSONDecodeError:
        return {
            "error": "Invalid JSON generated by LLM",
            "raw_output": json_text
        }
